version: "3.4"

services:
  prod:
    build: .
    image: backend_prod
    container_name: backend_prod
    ports:
      - 4001:5000 # modify the exported port as necessary
    environment:
      - PORT=5000 # this port is used to run the express app
      - NODE_ENV=production
    command: /usr/app/entrypoint.sh prod

  dev:
    build: .
    image: backend_dev
    container_name: backend_dev
    command: /usr/app/entrypoint.sh dev
    volumes:
      - .:/usr/app
    ports:
      - "3002:5000" # modify the exported port as necessary
    environment:
      - NODE_ENV=development
      - PORT=5000 # this port is used to run the express app
